# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [54]:
print(np.version.version)
print(np.show_config())


1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4429404432
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdeb

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
a = np.zeros((2,3,5))
a


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [6]:
a = np.ones((2,3,5))
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [8]:
from numpy.random import default_rng
a = default_rng(100).random((2,3,5))
a

array([[[0.83498163, 0.59655403, 0.28886324, 0.04295157, 0.9736544 ],
        [0.5964717 , 0.79026316, 0.91033938, 0.68815445, 0.18999147],
        [0.98147898, 0.28474005, 0.62927317, 0.58103648, 0.59991227]],

       [[0.53524811, 0.9957771 , 0.50194608, 0.77102258, 0.49416178],
        [0.99767449, 0.97862192, 0.39356804, 0.32192526, 0.86218065],
        [0.7993249 , 0.69143063, 0.40851785, 0.38976513, 0.1316484 ]]])


### 4. Print a.


In [9]:
a


array([[[0.83498163, 0.59655403, 0.28886324, 0.04295157, 0.9736544 ],
        [0.5964717 , 0.79026316, 0.91033938, 0.68815445, 0.18999147],
        [0.98147898, 0.28474005, 0.62927317, 0.58103648, 0.59991227]],

       [[0.53524811, 0.9957771 , 0.50194608, 0.77102258, 0.49416178],
        [0.99767449, 0.97862192, 0.39356804, 0.32192526, 0.86218065],
        [0.7993249 , 0.69143063, 0.40851785, 0.38976513, 0.1316484 ]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [10]:
b = np.ones((5,2,3))



### 6. Print b.


In [11]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [14]:
print(f"a is of size {a.size} and b is of size {b.size}, so yes both are the same size")


a is of size 30 and b is of size 30, so yes both are the same size



### 8. Are you able to add a and b? Why or why not?


In [16]:
a + b
#I am not able to add them due to different shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [36]:
c = np.transpose(b, (1,2,0))
c.shape

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
# It works now because a and c have the same shape



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print(d)
#I notice the difference is that d has the added ones (1) from c. Otherwise both are the same

[[[0.83498163 0.59655403 0.28886324 0.04295157 0.9736544 ]
  [0.5964717  0.79026316 0.91033938 0.68815445 0.18999147]
  [0.98147898 0.28474005 0.62927317 0.58103648 0.59991227]]

 [[0.53524811 0.9957771  0.50194608 0.77102258 0.49416178]
  [0.99767449 0.97862192 0.39356804 0.32192526 0.86218065]
  [0.7993249  0.69143063 0.40851785 0.38976513 0.1316484 ]]]
[[[1.83498163 1.59655403 1.28886324 1.04295157 1.9736544 ]
  [1.5964717  1.79026316 1.91033938 1.68815445 1.18999147]
  [1.98147898 1.28474005 1.62927317 1.58103648 1.59991227]]

 [[1.53524811 1.9957771  1.50194608 1.77102258 1.49416178]
  [1.99767449 1.97862192 1.39356804 1.32192526 1.86218065]
  [1.7993249  1.69143063 1.40851785 1.38976513 1.1316484 ]]]



### 12. Multiply a and c. Assign the result to e.


In [43]:
e = a * c




### 13. Does e equal to a? Why or why not?


In [ ]:
 e == a

# because multiplied by one does not change the original number, therefor a and e match


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [50]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [51]:
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [55]:
f[(d == d_max)] = 100
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d < d_mean) & (d > d_min)] = 25
f[(d == d_min)] = 0






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [56]:
print(d)
print(f)


[[[1.83498163 1.59655403 1.28886324 1.04295157 1.9736544 ]
  [1.5964717  1.79026316 1.91033938 1.68815445 1.18999147]
  [1.98147898 1.28474005 1.62927317 1.58103648 1.59991227]]

 [[1.53524811 1.9957771  1.50194608 1.77102258 1.49416178]
  [1.99767449 1.97862192 1.39356804 1.32192526 1.86218065]
  [1.7993249  1.69143063 1.40851785 1.38976513 1.1316484 ]]]
[[[ 75.  25.  25.   0.  75.]
  [ 25.  75.  75.  75.  25.]
  [ 75.  25.  75.  25.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [100.  75.  25.  25.  75.]
  [ 75.  75.  25.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]